export const FETCH_CHARACTER_REQUEST = "FETCH_CHARACTER_REQUEST"
export const FETCH_CHARACTER_REQUEST_SUCCESS = "FETCH_CHARACTER_REQUEST_SUCCESS"
export const FETCH_CHARACTER_REQUEST_ERROR = "FETCH_CHARACTER_REQUEST_ERROR"