export const FETCH_CHARACTER_REQUEST = "FETCH_CHARACTER_REQUEST"
export const FETCH_CHARACTER_REQUEST_SUCCESS = "FETCH_CHARACTER_REQUEST_SUCCESS"
export const FETCH_CHARACTER_REQUEST_ERROR = "FETCH_CHARACTER_REQUEST_ERROR"

export const TOGGLE_FILTER = "TOGGLE_FILTER"

export const DO_SEARCH = "DO_SEARCH"

export const DO_SORT = "DO_SORT"